bike/bike/urls.py
from django.contrib import admin
from django.urls import path, include





urlpatterns = [
    path('admin/', admin.site.urls),
    path('rent/', include('rent.urls')),
]

bike/rent/urls.py
from django.urls import path

from rent import views

urlpatterns = [
    # view bike
    path('', views.rent_view),

    # templates bike
    path('hi/', views.hi_view),
    path('hi2/', views.hi2_view),
]

bike/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rent/', include('rent.urls')),
    path('link/', include('link_app.urls')),
    path('form/', include('form_app.urls')),
    path('crud/', include('crud_app.urls')),
    path('orm/', include('orm_app.urls')),
]

crud_app/urls.py
from django.urls import path

from crud_app import views

app_name = 'crud_app'


urlpatterns = [
    # C z CRUD
    path('tasks/create/',
         views.task_create_view,
         name='task_create_view'
    ),

    # R z CRUD (lista)
    path('tasks/',
         views.task_list_view,
         name='task_list_view'
    ),

    # R z CRUD (szczegółu)
    path('tasks/<int:task_id>/',
         views.task_detail_view,
         name='task_detail_view'
    ),
# U z CRUD
    path('tasks/update/<int:task_id>/',
         views.task_update_view,
         name='task_update_view',
    ),

# D z CRUD
    path('tasks/delete/<int:task_id>/',
         views.task_delete_view,
         name='task_delete_view'
    ),

]

form_app/urls.py
from django.urls import path

from form_app import views

app_name = 'form_app'

urlpatterns = [
    path('hello-get/', views.hello_get, name='hello_get'),
    path('hello-post/', views.hello_post, name='hello_post'),
    path('show/', views.show, name='show'),
]

link_app/urls.py
from django.urls import path

from link_app import views

app_name = 'link_app'
urlpatterns = [
    path('first/', views.first_view, name='first'),
    path('second/', views.second_view, name='second'),
]

orm_app/urls.py
urlpatterns = [

]

rent/urls.py
from django.urls import path

from rent import views

urlpatterns = [
    # view bike
    path('', views.rent_view),

    # templates bike
    path('hi/', views.hi_view),
    path('hi2/', views.hi2_view),

    path('collection/', views.collection_view),
]

crud_app/models.py
# Create your models here.

form_app/models.py
# Create your models here.

link_app/models.py
from django.db import models

class Message(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField
    likes = models.IntegerField(default=0)
    verified = models.BooleanField(default=False)
    added_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField()

orm_app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=64)

def str(self):
    return "{self.name}"

class Country(models.Model):
    name = models.CharField(max_length=64)
    capitol = models.OneToOneField('Capital', on_delete=models.CASCADE)

class Capital(models.Model):
    name = models.CharField(max_length=64)

rent/models.py
# Create your models here.

bike/views.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rent/', include('rent.urls')),

# def bike(x):
#     return HttpResponse("rent a bike")
]

crud_app/views.py
from django.shortcuts import render, redirect, Http404

# Create your views here.
TASKS = [
    'kodowanie',
    'zmywanie'
]


# C z CRUD
def task_create_view(request):
    if request.method == "GET":
        return render(
            request,
            'crud_app/task_form.html'
        )
    elif request.method == "POST":
        data = request.POST

        task = data.get('task')
        if task:
            TASKS.append(task)

        return redirect('crud_app:task_list_view')


# R z CRUD (lista)
def task_list_view(request):

    tasks = TASKS

    return render(
        request,
        'crud_app/tasks.html',
        {'tasks': tasks}
    )


# R z CRUD (szczegółu)
def task_detail_view(request, task_id):
    if 0 < task_id <= len(TASKS):
        task = TASKS[task_id-1]

        return render(
            request,
            'crud_app/task_detail.html',
            {"task_id": task_id, "task": task}
        )

    else:
        raise Http404()

# U z CRUD
def task_update_view(request, task_id):
    if not 0 < task_id <= len(TASKS):
        raise Http404()
    else:
        task = TASKS[task_id-1]

    if request.method == "GET":
        return render(
            request,
            'crud_app/task_update.html',
            {'task_id': task_id, 'task': task}
        )
    elif request.method == "POST":
        data = request.POST

        task_new_name = data.get('task_name')
        if task_new_name:
            TASKS[task_id-1] = task_new_name

        return redirect('crud_app:task_list_view')




def task_delete_view(request, task_id):
    if not 0 < task_id <= len(TASKS):
        raise Http404()
    else:
        task = TASKS[task_id-1]

    if request.method == "GET":
        return render(
            request,
            'crud_app/task_delete.html',
            {'task_id': task_id, "task": task}
        )

    elif request.method == "POST":
        data = request.POST

        if 'yes' in data:
            TASKS.pop(task_id-1)

        return redirect('crud_app:task_list_view')

form_app/views.py
from django.shortcuts import render

# Create your views here.
def hello_get(request):
    data = request.GET

    name = None
    if 'first_name' in data:
        name = data['first_name']

    return render(
        request,
        'form_app/hello_get.html',
        {'name': name}
    )

def show(request):
    data = request.GET

    name = None
    if 'first_name' in data:
        name = data['first_name']

    return render(
        request,
        'form_app/show.html',
        {'name': name}
    )


def hello_post(request):
    data = request.POST
    name = data.get('first_name')

    return render(
        request,
        'form_app/hello_post.html',
        {'name': name}
    )

link_app/views.py
from django.shortcuts import render

# Create your views here.
def first_view(request):
    return render(
        request,
        'link_app/first.html'
    )

def second_view(request):
    return render(
        request,
        'link_app/second.html'
    )

orm_app/views.py
# Create your views here.

rent/views.py
from django.shortcuts import render, HttpResponse
#from django.utildjangs.html import escape

# Create your views here.
def rent_view(request):
    return HttpResponse("rent rent")

def hi_view(request):
    return HttpResponse("""
    <!DOCTYPE html>
    <html>
        <head>
        </head>
        <body>
            <h2>Hello, world!</h2>
        </body>
    </html>
    """)

def hi2_view(request):
    return render(request, 'rent.html')

def jurek_view(request):
    return HttpResponse("Witaj, Jurek!")


def jacek_view(request):
    return HttpResponse("Witaj, Jacek!")


def ksawier_view(request):
    return HttpResponse("Witaj, Ksawier!")


# Podatność XSS - przykład
def name_view(request, name):
    # importy powinny być zawsze na samej górze
#from django.utils.html import escape

    # always remember to escape your output
    print(name)
    escaped_name = escape(name)
    print(escaped_name)

    return HttpResponse(f"Witaj, {name}!")


# kontekst szablonu
def name_view2(request, name):
    return render(
        request,
        'rent2.html',
        {"name": name}
    )

def collection_view(request):
    fruits = [
        'apple',
        'banana',
        'pinaple',
        'blueberry',
        'orange',
    ]



    return render(
        request,
        'collection.html',
        {'fruits': fruits}
    )

bike/rent/templates/rent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>rent</title>
</head>
<body>
     <h2>Hello, world!</h2>
</body>
</html>

crud_app/templates/crud_app/task_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Czy na pewno chcesz usunąć zadanie o numerze {{ task_id }} ({{ task }})?</h3>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="TAK" name="yes">
        <input type="submit" value="NIE" name="no">
    </form>
     <a href="{% url 'crud_app:task_list_view' %}"><button>Lista zadań</button></a>
</body>
</html>

crud_app/templates/crud_app/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Szczegóły zadania o numerze {{ task_id }}</h3>
    {{ task }}
     <a href="{% url 'crud_app:task_list_view' %}"><button>Lista zadań</button></a>
</body>
</html>

crud_app/templates/crud_app/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="task_id">Nazwa zadania:</label>
        <input type="text" name="task" id="task_id">
        <input type="submit" value="Zarejestruj">
    </form>
     <a href="{% url 'crud_app:task_list_view' %}"><button>Lista zadań</button></a>
</body>
</html>

crud_app/templates/crud_app/task_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>Modyfikacja zadania numer {{ task_id }}</h3>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="task_name" value="{{ task }}">
        <input type="submit" value="Zmodyfikuj">
    </form>
    <a href="{% url 'crud_app:task_list_view' %}"><button>Lista zadań</button></a>
</body>
</html>

crud_app/templates/crud_app/tasks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="{% url 'crud_app:task_create_view' %}"><button>Nowe zadanie</button></a>
    <h3>Lista zadań</h3>
    <ol>
        {% for task in tasks %}
            <li><a href="{% url 'crud_app:task_detail_view' forloop.counter %}">{{ task }}</a>
                <a href="{% url 'crud_app:task_update_view' forloop.counter %}"><button>Edytuj</button></a>
                <a href="{% url 'crud_app:task_delete_view' forloop.counter %}"><button>Usuń</button></a>
            </li>
        {% endfor %}
    </ol>
</body>
</html>

form_app/templates/form_app/hello_get.html
<!DOCTYPE html>
<!--suppress Annotator -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if name %}
    Witaj {{ name }}!
{% endif %}

 <form>
  {# <form action="{% url 'form_app:show' %}"> #}
     <input type="text" name="first_name">
     <input type="submit" value="Przywitaj mnie">
 </form>
</body>
</html>

form_app/templates/form_app/hello_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if name %}
    Witaj {{ name }}!
{% endif %}

  <form method="POST">
      {% csrf_token %}
     <input type="text" name="first_name">
     <input type="submit" value="Przywitaj mnie">
 </form>
</body>
</html>

form_app/templates/form_app/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if name %}
        <p>Witaj, {{ name }}</p>
    {% else %}
        <p>Witaj, nieznajomy/nieznajoma</p>
    {% endif %}
</body>
</html>

link_app/templates/link_app/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> To jest 1 strona</h2>
Lore m ipsum

<p> przejdź do strony <a href="{% url 'link_app:second' %}">drugiej</a>.</p>
</body>
</html>

link_app/templates/link_app/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> To jest 2 strona</h2>
Lore m ipsum
<p> przejdź do strony <a href="{% url 'link_app:first' %}">pierwszej</a>.</p>
</body>
</html>

rent/templates/collection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> 3h 00  0620 backend3</h1>
    {{ fruits }}
<ul>
    {% for fruit in fruits %}
        <li>{{ fruit }}</li>
    {% endfor %}
</ul>

</body>
</html>

rent/templates/rent.html
{% load static %}
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'scripts/script.js' %}"></script>
</head>
<body>
   <h2>Hello, world!</h2>
</body>
</html>

rent/templates/rent2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Witaj, {{ name }}!    </h2>
</body>
</html>